Imports pkar.DotNetExtensions

Public NotInheritable Class ADR
    Inherits Page

    Private Sub Page_Loaded(sender As Object, e As RoutedEventArgs)
        uiQuery_Changed(Nothing, Nothing)
    End Sub

    Private Sub uiQuery_Changed(sender As Object, e As TextChangedEventArgs)

        If uiSubst Is Nothing Then Return

        Dim typy As List(Of ADRtyp) = _listaTypow.Where(
            Function(x)
                Return x.symbol.StartsWithCI(uiTyp.Text)
            End Function).ToList

        If typy.Count < 10 Then
            uiListaTypy.ItemsSource = typy
        Else
            uiListaTypy.ItemsSource = TooMuch()
        End If


        Dim queryById As Boolean = False
        If uiSubst.Text.Length > 0 AndAlso Char.IsDigit(uiSubst.Text, 0) Then
            queryById = True
        End If

        Dim subst As List(Of ADRtyp) = _listaSubst.Where(
            Function(x)
                If queryById Then
                    Return x.symbol.StartsWithCI(uiSubst.Text)
                End If
                Return x.opis.ContainsCI(uiSubst.Text)
            End Function).ToList

        If subst.Count < 10 Then
            uiListaSubst.ItemsSource = subst
        Else
            uiListaSubst.ItemsSource = TooMuch()
        End If

    End Sub

    Private Function TooMuch() As ADRtyp()
        Dim ret As ADRtyp() = {New ADRtyp("--", "Za dużo")}
        Return ret
    End Function


    Private Class ADRtyp
        Public Property symbol As String
        Public Property opis As String

        Public Sub New(symbol As String, opis As String)
            Me.symbol = symbol
            Me.opis = opis
        End Sub
    End Class

    Private _listaTypow As ADRtyp() =
        {
        New ADRtyp("2", "emisja gazu spowodowana ciśnieniem lub reakcją chemiczną"),
New ADRtyp("3", "zapalność cieczy (par) i gazów"),
New ADRtyp("4", "zapalność materiałów stałych"),
New ADRtyp("5", "działanie utleniające (podtrzymujące palenie)"),
New ADRtyp("6", "działanie trujące"),
New ADRtyp("7", "działanie promieniotwórcze"),
New ADRtyp("8", "działanie żrące"),
New ADRtyp("9", "jako pierwsza cyfra:"),
New ADRtyp("", "zagrożenie dla środowiska; różne niebezpieczne substancje"),
New ADRtyp("", "Jako 2. lub 3. cyfra:"),
New ADRtyp("", "zagrożenie samorzutną i gwałtowną reakcją"),
New ADRtyp("0", "brak dodatkowego zagrożenia"),
New ADRtyp("X", "całkowity zakaz konaktu z wodą"),
New ADRtyp("20", "gaz duszący lub niestwarzający dodatkowego zagrożenia"),
New ADRtyp("22", "gaz skroplony schłodzony, duszący"),
New ADRtyp("223", "gaz skroplony schłodzony palny"),
New ADRtyp("225", "gaz skroplony schłodzony utleniający (podtrzymujący palenie)"),
New ADRtyp("23", "gaz palny"),
New ADRtyp("238", "gaz palny. żrący"),
New ADRtyp("239", "gaz palny mogący powodować samorzutną i gwałtowną reakcję"),
New ADRtyp("25", "gaz utleniający (podtrzymujący palenie)"),
New ADRtyp("26", "gaz trujący"),
New ADRtyp("263", "gaz trujący, palny"),
New ADRtyp("265", "gaz trujący i utleniający (podtrzymujący palenie)"),
New ADRtyp("266", "gaz silnie trujący"),
New ADRtyp("268", "gaz trujący i żrący"),
New ADRtyp("286", "gaz żrący i trujący"),
New ADRtyp("28", "gaz żrący"),
New ADRtyp("30", "ciecz zapalna (temp. zapłonu od 23 °C do 100 °C)"),
New ADRtyp("33", "ciecz łatwo zapalna (temp. zapłonu niższa od 23 °C)"),
New ADRtyp("323", "materiał ciekły zapalny, reagujący z wodą, wydzielający gazy palne"),
New ADRtyp("X323", "materiał ciekły zapalny, reagujący niebezpiecznie z wodą, wydzielający gazy palne"),
New ADRtyp("333", "ciecz samozapalna"),
New ADRtyp("X333", "ciecz samozapalna reagująca niebezpiecznie z wodą"),
New ADRtyp("336", "ciecz łatwo zapalna i trująca"),
New ADRtyp("338", "ciecz łatwo zapalna i żrąca"),
New ADRtyp("X338", "ciecz łatwo zapalna i żrąca reagująca niebezpiecznie z wodą"),
New ADRtyp("339", "ciecz łatwo zapalna mogąca powodować samorzutną i gwałtowną reakcję"),
New ADRtyp("39", "ciecz zapalna mogąca powodować samorzutną i gwałtowną reakcję"),
New ADRtyp("40", "materiał stały zapalny"),
New ADRtyp("X423", "materiał stały zapalny reagujący niebezpiecznie z wodą, wydzielający gaz zapalny"),
New ADRtyp("44", "materiał stały zapalny, w podwyższonej temp., znajdujący się w stanie stopionym"),
New ADRtyp("446", "materiał stały zapalny i trujący, w podwyższonej temp., znajdujący się w stanie stopionym"),
New ADRtyp("46", "materiał stały zapalny i trujący"),
New ADRtyp("50", "materiał utleniający (podtrzymujący palenie)"),
New ADRtyp("539", "nadtlenek organiczny zapalny"),
New ADRtyp("558", "materiał silnie utleniający (podtrzymujący palenie) i żrący"),
New ADRtyp("559", "materiał silnie utleniający (podtrzymujący palenie) mogący powodować samorzutną i gwałtowną reakcję"),
New ADRtyp("589", "materiał utleniający (podtrzymujący palenie) i żrący mogący powodować samorzutną i gwałtowną reakcję"),
New ADRtyp("60", "materiał trujący lub szkodliwy"),
New ADRtyp("606", "materiał zakaźny"),
New ADRtyp("63", "materiał trujący lub szkodliwy i zapalny (temp. zapłonu od 21 °C do 55 °C)"),
New ADRtyp("638", "materiał trujący lub szkodliwy oraz zapalny (temp. zapłonu od 21 °C do 55 °C) i żrący"),
New ADRtyp("66", "materiał silnie trujący"),
New ADRtyp("663", "materiał silnie trujący i zapalny (temp. zapłonu nie wyższa niż 55 °C)"),
New ADRtyp("68", "materiał trujący lub szkodliwy i żrący"),
New ADRtyp("69", "materiał trujący lub szkodliwy mogący powodować samorzutną i gwałtowną reakcję"),
New ADRtyp("76", "materiał radioaktywny i trujący lub szkodliwy"),
New ADRtyp("78", "materiał radioaktywny i żrący"),
New ADRtyp("80", "materiał żrący lub wykazujący mniejszy stopień działania żrącego"),
New ADRtyp("X80", "materiał żrący lub wykazujący mniejszy stopień działania żrącego, reagujący niebezpiecznie z wodą"),
New ADRtyp("83", "materiał żrący lub wykazujący mniejszy stopień działania żrącego oraz zapalny (temp. zapłonu od 21 °C do 55 °C)"),
New ADRtyp("839", "materiał żrący lub wykazujący mniejszy stopień działania żrącego oraz zapalny (temp. zapłonu od 21 °C do 55 °C), mogący powodować samorzutną i gwałtowną reakcję"),
New ADRtyp("85", "materiał żrący lub wykazujący mniejszy stopień działania żrącego oraz utleniający (podtrzymujący palenie)"),
New ADRtyp("856", "materiał żrący lub wykazujący mniejszy stopień działania żrącego oraz utleniający (podtrzymujący palenie) i trujący"),
New ADRtyp("86", "materiał żrący lub wykazujący mniejszy stopień działania żrącego oraz trujący"),
New ADRtyp("88", "materiał silnie żrący"),
New ADRtyp("X88", "materiał silnie żrący, reagujący niebezpiecznie z woda"),
New ADRtyp("883", "materiał silnie żrący i zapalny (temp. zapłonu od 21 °C do 55 °C)"),
New ADRtyp("885", "materiał silnie żrący i utleniający (podtrzymujący palenie)"),
New ADRtyp("886", "materiał silnie żrący i trujący"),
New ADRtyp("X886", "materiał silnie żrący i trujący, reagujący niebezpiecznie z wodą"),
New ADRtyp("89", "materiał żrący lub wykazujący mniejszy stopień działania żrącego, mogący powodować samorzutną i gwałtowną reakcję"),
New ADRtyp("90", "materiał zagrażający środowisku, różne materiały niebezpieczne"),
New ADRtyp("99", "różne materiały niebezpieczne przewożone w podwyższonej temperaturze")
        }

    Private _listaSubst As ADRtyp() =
        {
        New ADRtyp("1001", "Acetylen rozpuszczony"),
New ADRtyp("1002", "Powietrze sprężone"),
New ADRtyp("1003", "Powietrze ciekłe schłodzone"),
New ADRtyp("1005", "Amoniak"),
New ADRtyp("1006", "Sprężony argon"),
New ADRtyp("1008", "Trójfluorek boru"),
New ADRtyp("1009", "Bromotrójfluorometan (R-13B1)"),
New ADRtyp("1010", "Butadien-1,3"),
New ADRtyp("1011", "Butan"),
New ADRtyp("1012", "Butylen-1"),
New ADRtyp("1013", "Dwutlenek węgla"),
New ADRtyp("1016", "Tlenek węgla"),
New ADRtyp("1017", "Chlor"),
New ADRtyp("1018", "Chlorodwufluorometan (R-22)"),
New ADRtyp("1020", "Chloropięciofluoroetan (R-115)"),
New ADRtyp("1022", "Chlorotrójfluorometan (R-13) (trójfluorochlorometan)"),
New ADRtyp("1023", "Gaz węglowy, sprężony"),
New ADRtyp("1026", "Cyjan"),
New ADRtyp("1027", "Cyklopropan"),
New ADRtyp("1028", "Dwuchlorodwufluorometan (R-12)"),
New ADRtyp("1029", "Dwuchlorofluorometan (R-21)"),
New ADRtyp("1032", "Dwuroetyloamina bezwodna"),
New ADRtyp("1033", "Eter dwumetylowy (tlenek metylu)"),
New ADRtyp("1035", "Etan"),
New ADRtyp("1036", "Etyloamina bezwodna (monoetyloamina)"),
New ADRtyp("1037", "Chlorek etylu (chloroetan)"),
New ADRtyp("1038", "Etylen (schłodzony)"),
New ADRtyp("1039", "Eter metylowo-etylowy"),
New ADRtyp("1040", "Tlenek etylenu z azotem"),
New ADRtyp("1041", "Tlenek etylenu"),
New ADRtyp("1045", "Fluor, sprężony"),
New ADRtyp("1046", "Hel, sprężony"),
New ADRtyp("1048", "Bromowodór"),
New ADRtyp("1049", "Wodór, sprężony"),
New ADRtyp("1050", "Chlorowodór"),
New ADRtyp("1051", "Cyjanowodór"),
New ADRtyp("1052", "Kwas fluorowodorowy bezwodny (fluorowodór)"),
New ADRtyp("1053", "Siarkowodór skroplony"),
New ADRtyp("1055", "Izobutylen (izobuten)"),
New ADRtyp("1056", "Krypton, sprężony"),
New ADRtyp("1057", "Zapalniczki"),
New ADRtyp("1060", "Mieszanina metyloacetylenu/propadienu z węglowodorami (mieszaniny Pl i P2)"),
New ADRtyp("1061", "Metyloamina bezwodna"),
New ADRtyp("1062", "Bromek metylu (bromometan, monobromometan)"),
New ADRtyp("1063", "Chlorek metylu (chlorometan)"),
New ADRtyp("1064", "Merkaptan metylowy (metanotiol)"),
New ADRtyp("1065", "Neon, sprężony"),
New ADRtyp("1066", "Azot, sprężony"),
New ADRtyp("1067", "Dwutlenek azotu NO2 (czterotlenek azotu N2O4)"),
New ADRtyp("1069", "Chlorek nitrozylu (NOCl)"),
New ADRtyp("1070", "Podtlenek azotu N2O (gaz rozweselający)"),
New ADRtyp("1071", "Gaz olejowy, sprężony"),
New ADRtyp("1072", "Tlen, sprężony"),
New ADRtyp("1073", "Tlen (schłodzony)"),
New ADRtyp("1075", "Gaz ziemny, skroplony"),
New ADRtyp("1076", "Tlenochlorek węgla (fosgen)"),
New ADRtyp("1077", "Propylen"),
New ADRtyp("1078", "Mieszaniny F l, F2 i F3"),
New ADRtyp("1079", "Dwutlenek siarki"),
New ADRtyp("1080", "Sześciofluorek siarki"),
New ADRtyp("1083", "Trójmetyloamina"),
New ADRtyp("1085", "Bromek winylu"),
New ADRtyp("1086", "Chlorek winylu"),
New ADRtyp("1087", "Eter metylowinylowy (tlenek metylowinylowy)"),
New ADRtyp("1088", "Acetal (acetal dwuetylowy, dwuetoksy-l,1-etan)"),
New ADRtyp("1089", "Aldehyd octowy (acetaldehyd)"),
New ADRtyp("1090", "Aceton (dwumetyloketon)"),
New ADRtyp("1092", "Akroleina (aldehyd akrylowy, aldehyd allilowy)"),
New ADRtyp("1093", "Akrylonitryl"),
New ADRtyp("1095", "Alkohol skażony (denaturat)"),
New ADRtyp("1098", "Alkohol allilowy"),
New ADRtyp("1099", "Bromek allilu (bromopropylen)"),
New ADRtyp("1100", "Chlorek allilu (chloropropylen)"),
New ADRtyp("1104", "Octan amylu (ester amylowy kwasu octowego)"),
New ADRtyp("1105", "Pentanole I,II,i III-rz."),
New ADRtyp("1106", "Alkohol amylowy III-rz. i inne alkohole amylowe niż III rz."),
New ADRtyp("1109", "Mrówczan amylu"),
New ADRtyp("1112 i 1113", "Azotan amylu"),
New ADRtyp("1114", "Benzen"),
New ADRtyp("1120", "Alkohol n-butylowy (n-butanol)"),
New ADRtyp("1121", "Alkohol butylowy II-rz. (butanol II-rz.)"),
New ADRtyp("1122", "Alkohol butylowy III-rz. (butanol III-rz., 2-metylo--2-hydroksypropan, 2-metylopropanol-2)"),
New ADRtyp("1123", "Octan n-butylu (ester butylowy kwasu octowego)"),
New ADRtyp("1124", "Octan II-rz. butylu (ester butylowy II-rz. kwasu octowego)"),
New ADRtyp("1125", "Butyloamina"),
New ADRtyp("1126", "m-Bromobutany (bromek butylu, bromobutany)"),
New ADRtyp("1127", "Chlorek n-butylu"),
New ADRtyp("1128", "Mrówczan n-butylu"),
New ADRtyp("1129", "Aldehyd masłowy (butanal-1)"),
New ADRtyp("1131", "Dwusiarczek węgla"),
New ADRtyp("1133", "Kleje"),
New ADRtyp("1134", "Chlorobenzen (monochlorobenzen)"),
New ADRtyp("1135", "Etylenochlorohydryna (chlorohydryna etylenowa)"),
New ADRtyp("1136", "Destylaty smoły"),
New ADRtyp("1139", "Farby ochronne"),
New ADRtyp("1143", "Aldehyd krotonowy (krotonaldehyd, metyloakroleina)"),
New ADRtyp("1145", "Cykloheksan"),
New ADRtyp("1146", "Cyklopentan"),
New ADRtyp("1147", "Dekahydronaftaleny (dekaliny)"),
New ADRtyp("1148", "Dwuacetonoalkohol (alkohol dwuacetonowy)"),
New ADRtyp("1149", "Eter dwubutylowy (eter n-butylowy)"),
New ADRtyp("1150", "1,2-Dwuchloroetylen (dwuchlorek acetylenu)"),
New ADRtyp("1152", "Dwuchloropentan"),
New ADRtyp("1153", "Eter dietylowy"),
New ADRtyp("1154", "Dwuetyloamina"),
New ADRtyp("1155", "Eter etylowy (eter dwuetylowy, eter siarkowy)"),
New ADRtyp("1156", "Keton dietylowy"),
New ADRtyp("1157", "Keton dwuizobutylowy"),
New ADRtyp("1158", "Dwuizopropyloamina"),
New ADRtyp("1159", "Eter dwuizopropylowy"),
New ADRtyp("1160", "Dwumetyloamina w roztworze wodnym o temperaturze zapłonu niższej niż 21 °C"),
New ADRtyp("1161", "Węglan dwumetylu"),
New ADRtyp("1163", "1,1-Dwumetylohydrazyna (dimetylohydrazyna niesymetryczna, UDMH)"),
New ADRtyp("1165", "Dioksan (eter dwuetylenowy)"),
New ADRtyp("1167", "Eter dwuwinylowy"),
New ADRtyp("1169", "Ekstrakty i aromaty"),
New ADRtyp("1170", "Alkohol etylowy (etanol)"),
New ADRtyp("1172", "Octan etoksyetylowy"),
New ADRtyp("1173", "Octan etylu (ester etylowy kwasu octowego)"),
New ADRtyp("1175", "Etylobenzen"),
New ADRtyp("1176", "Trietylek boru"),
New ADRtyp("1180", "Maślan n-etylu"),
New ADRtyp("1181", "Chlorooctan etylu"),
New ADRtyp("1182", "Chloromrówczan etylu"),
New ADRtyp("1184", "1,2-Dwuchloroetan"),
New ADRtyp("1185", "Etylenoimina"),
New ADRtyp("1190", "Mrówczan etylu"),
New ADRtyp("1193", "Metyloetyloketon (keton etylometylowy)"),
New ADRtyp("1195", "Propionian etylu"),
New ADRtyp("1198", "Formaldehyd"),
New ADRtyp("1199", "Furfurol (furfural, aldehyd furfurylowy)"),
New ADRtyp("1202", "Olej napędowy do silników Diesla (węglowodory ciekłe o temperaturze zapłonu ponad 55 do 100 °C)"),
New ADRtyp("1203", "Benzyna (węglowodory ciekłe o temperaturze zapłonu niższej niż 21 °C)"),
New ADRtyp("1210", "Farby drukarskie o temperaturze zapłonu niższej niż 21 °C oraz o temperaturze zapłonu co najmniej 21 °C zawierające do 30% ciał stałych"),
New ADRtyp("1212", "Alkohol izobutylowy (izobutanol)"),
New ADRtyp("1213", "Octan izobutylu"),
New ADRtyp("1218", "Izopren"),
New ADRtyp("1219", "Alkohol izopropylowy (izopropanol)"),
New ADRtyp("1220", "Octan izopropylu"),
New ADRtyp("1221", "Izopropyloamina"),
New ADRtyp("1222", "Azotan izopropylu"),
New ADRtyp("1223", "Benzyna ciężka, nafta (węglowodory ciekłe o temperaturze zapłonu od 21 do 55 °C)"),
New ADRtyp("1229", "Tlenek mezytylu"),
New ADRtyp("1230", "Alkohol metylowy (karbinol, metanol, spirytus drzewny)"),
New ADRtyp("1231", "Octan metylu"),
New ADRtyp("1234", "Metylal (dwumetoksymetan)"),
New ADRtyp("1235", "Metyloamina w roztworze (monometyloamina w roztworze)"),
New ADRtyp("1238", "Chloromrówczan metylu"),
New ADRtyp("1239", "Chlorodwumetyloeter (eter metylochlorometylowy)"),
New ADRtyp("1242", "Dwuchlorosilan metylu"),
New ADRtyp("1243", "Mrówczan metylu (ester metylowy kwasu mrówkowego)"),
New ADRtyp("1245", "Metyloizobutyloketon"),
New ADRtyp("1247", "Metakrylan metylu"),
New ADRtyp("1248", "Propionian metylu"),
New ADRtyp("1250", "Trójchlorosilan metylu (trójchlorometylosilan)"),
New ADRtyp("1251", "Metylowinyloketon"),
New ADRtyp("1264", "Paraldehyd"),
New ADRtyp("1265", "Izopentan (pentan)"),
New ADRtyp("1274", "Alkohol propylowy (propanol)"),
New ADRtyp("1275", "Aldehyd propionowy (propanal)"),
New ADRtyp("1276", "Octan propylu"),
New ADRtyp("1279", "Dwuchlorek propylenu (1,2-dwuchloropropan)"),
New ADRtyp("1280", "Tlenek propylenu"),
New ADRtyp("1282", "Pirydyna"),
New ADRtyp("1292", "Krzemian etylu"),
New ADRtyp("1294", "Toluen (metylobenzen)"),
New ADRtyp("1295", "Krzemochloroform (trójchlorosilan)"),
New ADRtyp("1296", "Trójetyloamina"),
New ADRtyp("1297", "Trójmetyloamina w roztworze"),
New ADRtyp("1298", "Trójmetylochlorosilan"),
New ADRtyp("1299", "Terpentyna (benzyna lakowa)"),
New ADRtyp("1301", "Octan winylu"),
New ADRtyp("1303", "1,1-Dwuchloroetylen (chlorek winylidenu)"),
New ADRtyp("1307", "Ksyleny (dwumetylobenzen)"),
New ADRtyp("1334", "Naftalen – stały"),
New ADRtyp("1328", "Urotropina"),
New ADRtyp("1344", "Kwas pikrynowy"),
New ADRtyp("1428", "Sód"),
New ADRtyp("1495", "Chloran sodu stały"),
New ADRtyp("1541", "Acetonocyjanohydryna (cyjanohydryna acetonu)"),
New ADRtyp("1547", "Anilina"),
New ADRtyp("1553", "Kwas arsenowy w roztworze wodnym"),
New ADRtyp("1578", "Chloronitrobenzeny"),
New ADRtyp("1580", "Chloropikryna"),
New ADRtyp("1591", "o-Dwuchlorobenzen"),
New ADRtyp("1593", "Chlorek metylenu (dwuchlorometan)"),
New ADRtyp("1594", "Siarczan dwuetylu (siarczan etylu)"),
New ADRtyp("1595", "Siarczan dwumetylu (siarczan metylu)"),
New ADRtyp("1600", "Dwunitrotolueny"),
New ADRtyp("1603", "Bromooctan etylu"),
New ADRtyp("1604", "Etylenodwuamina"),
New ADRtyp("1605", "Dwubromoetan (dwubromek etylenu, bromek etylenu)"),
New ADRtyp("1613", "Cyjanowodór w roztworze wodnym (kwas cyjanowodorowy w roztworze wodnym zawierającym do 20% czystego kwasu)"),
New ADRtyp("1648", "Acetonitryl (cyjanek metylu)"),
New ADRtyp("1649", "Alkilaty ołowiu i ich mieszaniny z organicznymi związkami chlorowców (ciecz etylowa, czteroetylek ołowiu, czterometylek ołowiu)"),
New ADRtyp("1662", "Nitrobenzen"),
New ADRtyp("1664", "m-Nitrotolueny"),
New ADRtyp("1665", "Nitroksyleny"),
New ADRtyp("1670", "Nadchlorometylomerkaptan"),
New ADRtyp("1673", "Fenylenodwuaminy"),
New ADRtyp("1695", "Chloroaceton"),
New ADRtyp("1702", "1,1,2,2-Czterochloroetan"),
New ADRtyp("1708", "Toluidyny"),
New ADRtyp("1709", "2,4-Toluenodwuamina (2,4-dwuaminotoluen)"),
New ADRtyp("1715", "Bezwodnik kwasu octowego"),
New ADRtyp("1717", "Chlorek acetylu"),
New ADRtyp("1727", "Dwufluorek amonu w roztworze (fluorek amonowy kwaśny w roztworze)"),
New ADRtyp("1730", "Pięciochlorek antymonu"),
New ADRtyp("1736", "Chlorek benzoilu"),
New ADRtyp("1738", "Chlorek benzylu"),
New ADRtyp("1742", "Fluorek boru i kwas octowy, zespolone"),
New ADRtyp("1744", "Brom"),
New ADRtyp("1750", "Kwasy chlorooctowe ciekłe (kwas dwuchlorooctowy, kwas jednochlorooctowy)"),
New ADRtyp("1752", "Chlorek chloroacetylu"),
New ADRtyp("1754", "Kwas chlorosulfonowy"),
New ADRtyp("1765", "Chlorek dwuchloroacetylu"),
New ADRtyp("1775", "Kwas fluoroborowy w roztworze wodnym zawierającym do 78% czystego kwasu"),
New ADRtyp("1778", "Kwas krzemofluorowodorowy"),
New ADRtyp("1779", "Kwas mrówkowy zawierający co najmniej 70% czystego kwasu"),
New ADRtyp("1783", "Sześciometylenodwuamina"),
New ADRtyp("1788", "Bromowodór w roztworze (kwas bromowodorowy w roztworze)"),
New ADRtyp("1789", "Kwas solny w roztworze (chlorowodór w roztworze)"),
New ADRtyp("1790", "Kwas fluorowodorowy w roztworze wodnym zawierającym ponad 60%, ale nie więcej niż 85% kwasu fluorowodorowego bezwodnego"),
New ADRtyp("1791", "Podchlorynu roztwór zawierający ponad 50 g aktywnego chloru na litr lub do 50 g aktywnego chloru na litr"),
New ADRtyp("1706", "Mieszaniny nitrozowe kwasu siarkowego zawierające do 30 lub ponad 30% czystego kwasu azotowego"),
New ADRtyp("1802", "Kwas nadchlorowy w roztworze wodnym zawierającym do 50% czystego kwasu"),
New ADRtyp("1808", "Trójbromek fosforu"),
New ADRtyp("1809", "Trójchlorek fosforu"),
New ADRtyp("1810", "Tlenochlorek fosforu"),
New ADRtyp("1814", "Ług potasowy (wodorotlenek potasu)"),
New ADRtyp("1815", "Chlorek propionylu"),
New ADRtyp("1818", "Czterochlorek krzemu"),
New ADRtyp("1819", "Glinian sodu w roztworze"),
New ADRtyp("1824", "Ług sodowy (wodorotlenek sodu w roztworze)"),
New ADRtyp("1828", "Dwuchlorek dwusiarki i dwuchlorek dwusiarki stabilizowany"),
New ADRtyp("1829", "Bezwodnik kwasu siarkowego (trójtlenek siarki)"),
New ADRtyp("1830", "Kwas siarkowy zawierający do 85% czystego kwasu"),
New ADRtyp("1831", "Oleum (kwas siarkowy dymiący)"),
New ADRtyp("1832", "Kwas siarkowy odpadkowy, całkowicie zdenitrowany"),
New ADRtyp("1834", "Chlorek sulfurylu"),
New ADRtyp("1836", "Chlorek tionylu"),
New ADRtyp("1838", "Czterochlorek tytanu"),
New ADRtyp("1842", "Kwas octowy lodowaty i jego roztwory zawierające ponad 80% czystego kwasu"),
New ADRtyp("1846", "Czterochlorek węgla (czterochlorometan)"),
New ADRtyp("1848", "Kwas propionowy"),
New ADRtyp("1849", "Siarczek sodu w roztworze"),
New ADRtyp("1863", "Paliwo lotnicze"),
New ADRtyp("1866", "Żywice w roztworze, w cieczach zapalnych o temperaturze zapłonu niższej niż 21 °C lub o temperaturze zapłonu od 21 do 100 °C z zawartością do 30% żywicy"),
New ADRtyp("1873", "Kwas nadchlorowy w roztworze wodnym zawierającym ponad 50%, ale nie więcej niż 72,5% czystego kwasu"),
New ADRtyp("1886", "Chlorek benzylidenu"),
New ADRtyp("1888", "Chloroform (trójchlorometan)"),
New ADRtyp("1891", "Bromek etylu (bromoetan)"),
New ADRtyp("1908", "Chloryn sodu w roztworze"),
New ADRtyp("1915", "Cykloheksanon"),
New ADRtyp("1916", "2,2-Dwuchloroetyloeter (eter dwuchloroetylowy)"),
New ADRtyp("1917", "Akrylan etylu"),
New ADRtyp("1918", "Kumen (izopropylobenzen)"),
New ADRtyp("1919", "Akrylan metylu"),
New ADRtyp("1921", "Propylenoimina"),
New ADRtyp("1935", "Cyjanki nieorganiczne w roztworach"),
New ADRtyp("1940", "Kwas tioglikolowy"),
New ADRtyp("1951", "Argon (schłodzony)"),
New ADRtyp("1958", "Dwuchloroczterofluoroetan (R 114)"),
New ADRtyp("1959", "1,1-Dwufluoroetylen (R 1132a)"),
New ADRtyp("1962", "Etylen"),
New ADRtyp("1963", "Hel ciekły (schłodzony)"),
New ADRtyp("1965", "Mieszaniny węglowodorów (gazy skroplone), mieszaniny A, AO, Al, B i C"),
New ADRtyp("1969", "Izobutan"),
New ADRtyp("1972", "Gaz ziemny (metan) schłodzony"),
New ADRtyp("1973", "Mieszanina gazów R 502"),
New ADRtyp("1974", "Bromochlorodwufluorometan (chlorodwufluorobromometan) (R 12 B1)"),
New ADRtyp("1977", "Azot (schłodzony)"),
New ADRtyp("1978", "Propan"),
New ADRtyp("1984", "Trójfluorometan (R 23) (fluoroform)"),
New ADRtyp("1987", "Alkohole ciekłe nie trujące, czyste lub w mieszaninach (alkohol 2-etylobutylowy, alkohol 2-etyloheksylowy, heptanole, heksanole, oktanole)"),
New ADRtyp("1989", "Aldehyd heptylowy (heptanal)"),
New ADRtyp("1990", "Benzaldehyd (aldehyd benzoesowy)"),
New ADRtyp("1991", "Chloropren (chlorobutadien)"),
New ADRtyp("2014", "Nadtlenek wodoru w roztworze wodnym zawierającym ponad 6%, ale nie więcej niż 60% nadtlenku wodoru (roztwór nadtlenku wodoru)"),
New ADRtyp("2015", "Nadtlenek wodoru stabilizowany i w roztworze wodnym zawierającym ponad 60% nadtlenku wodoru stabilizowanego"),
New ADRtyp("2019", "Chloroaniliny ciekłe"),
New ADRtyp("2021", "Dwuchlorofenole (o-chlorofenol)"),
New ADRtyp("2022", "Kwas krezolowy"),
New ADRtyp("2023", "Epichlorohydryna"),
New ADRtyp("2029", "Hydrazyna w roztworach wodnych zawierających ponad 64%, ale nie więcej niż 72% hydrazyny"),
New ADRtyp("2030", "Hydrazyna w roztworze wodnym zawierającym nie więcej niż 64% hydrazyny"),
New ADRtyp("2031", "Kwas azotowy zawierający ponad 55%, ale nie więcej niż 70% czystego kwasu"),
New ADRtyp("2032", "Kwas azotowy zawierający ponad 70% czystego kwasu"),
New ADRtyp("2045", "Aldehyd izomasłowy"),
New ADRtyp("2047", "Dwuchloropropen"),
New ADRtyp("2048", "Dwucyklopentadien techniczny"),
New ADRtyp("2849", "Dwuetylobenzen"),
New ADRtyp("2050", "Dwuizobutyleny"),
New ADRtyp("2053", "Metyloizobutylokarbinol (alkohol metyloamylowy)"),
New ADRtyp("2055", "Styren (winylobenzen)"),
New ADRtyp("2056", "Czterowodorofuran (tetrahydrofuran)"),
New ADRtyp("2057", "Propylenu trimer (trój propylen)"),
New ADRtyp("2073", "Amoniak rozpuszczony w wodzie z zawartością ponad 35%, ale nie większą niż 50% amoniaku"),
New ADRtyp("2074", "Akryloamid w roztworze"),
New ADRtyp("2075", "Aldehyd trójchlorooctowy (chloral bezwodny)"),
New ADRtyp("2076", "Krezole (metylofenole)"),
New ADRtyp("2078", "2,4-Toluenodwuizocyjanian (2-4-dwuizocyjanianotoluen)"),
New ADRtyp("2116", "Wodoronadtlenek kumenu zawierający do 95% nadtlenku"),
New ADRtyp("2125", "Wodoronadtlenek p-mentanu zawierający do 95% nadtlenku"),
New ADRtyp("2162", "Wodoronadtlenek pinanu zawierający do 95% nadtlenku"),
New ADRtyp("2171", "Wodoronadtlenek dwuizopropylobenzenu"),
New ADRtyp("2187", "Dwutlenek węgla ciekły (schłodzony)"),
New ADRtyp("2205", "Adyponitryl (nitryl kwasu adypinowego)"),
New ADRtyp("2219", "Eter alliloglicydowy"),
New ADRtyp("2222", "Anizol (metoksybenzen)"),
New ADRtyp("2226", "Chlorek benzylidynu (fenylochloroform)"),
New ADRtyp("2227", "Metakrylan butylu"),
New ADRtyp("2233", "p-Chloro-o-anizydyna"),
New ADRtyp("2238", "Chlorotolueny (o-, m-, p-)"),
New ADRtyp("2243", "Octan cykloheksylu"),
New ADRtyp("2245", "Cyklopentanon"),
New ADRtyp("2248", "Dwu (n-butylo) amina"),
New ADRtyp("2251", "Dwucykloheptadien"),
New ADRtyp("2253", "N.N-Dwumetyloanilina"),
New ADRtyp("2256", "Cykloheksen"),
New ADRtyp("2257", "Potas"),
New ADRtyp("2258", "Propylenodwuamina (1,2-dwuaminopropan)"),
New ADRtyp("2259", "Trójetylenoczteroamina"),
New ADRtyp("2260", "Trójpropyloamina"),
New ADRtyp("2261", "Ksylenole (dwumetylofenole)"),
New ADRtyp("2264", "N.N-Dwumetylocykloheksyloamina"),
New ADRtyp("2269", "Dwupropylenotrójamina"),
New ADRtyp("2270", "Etyloamina w roztworze 50 do 70%"),
New ADRtyp("2271", "Etyloamyloketon"),
New ADRtyp("2272", "N-Etyloanilina"),
New ADRtyp("2276", "2-Etyloheksyloamina"),
New ADRtyp("2277", "Metakrylan etylu"),
New ADRtyp("2279", "Sześciochlorobutadien"),
New ADRtyp("2283", "Metakrylan izobutylu"),
New ADRtyp("2284", "Nitryl kwasu izomasłowego"),
New ADRtyp("2295", "Chlorooctan metylu"),
New ADRtyp("2296", "Metylocykloheksan"),
New ADRtyp("2297", "Metylocykloheksanon"),
New ADRtyp("2298", "Metylocyklopentan"),
New ADRtyp("2299", "Dwuchlorooctan metylu"),
New ADRtyp("2300", "2-Metylo-5-etylopirydyna"),
New ADRtyp("2301", "2-Metylofuran"),
New ADRtyp("2303", "a-Metylostyren (2-fenylopropen)"),
New ADRtyp("2304", "Naftalen w stanie stopionym"),
New ADRtyp("2308", "Kwas nitrozylosiarkowy w roztworze siarkowym"),
New ADRtyp("2311", "Fenetydyny (etoksyaniliny)"),
New ADRtyp("2312", "Fenol stopiony"),
New ADRtyp("2319", "Olejek terpentynowy (terpentyna oczyszczona)"),
New ADRtyp("2321", "Trójchlorobenzeny ciekłe"),
New ADRtyp("2324", "Trójizobutylen"),
New ADRtyp("2325", "1,3,5-Trójmetylobenzen (mezytylen)"),
New ADRtyp("2334", "Alliloamina"),
New ADRtyp("2348", "Akrylan n-butylu"),
New ADRtyp("2353", "Chlorek kwasu masłowego (chlorek butyrylu)"),
New ADRtyp("2356", "Chlorek izopropylu (2-chloropropan)"),
New ADRtyp("2357", "Cykloheksyloamina"),
New ADRtyp("2361", "Dwuizobutyloamina"),
New ADRtyp("2363", "Merkaptan etylowy"),
New ADRtyp("2364", "n-Propylobenzen"),
New ADRtyp("2366", "Węglan dwuetylu"),
New ADRtyp("2367", "Aldehyd ot-metylowalerianówy"),
New ADRtyp("2381", "Dwusiarczek dwumetylu"),
New ADRtyp("2386", "1-Etylopiperydyna"),
New ADRtyp("2387", "Fluorobenzen"),
New ADRtyp("2388", "Fluorotolueny"),
New ADRtyp("2412", "Czterowodorotiofen (tetrahydrotipfen)"),
New ADRtyp("2416", "Boran trójmetylu"),
New ADRtyp("2426", "Azotan amonu, gorący stężony roztwór wodny"),
New ADRtyp("2427", "Chloran potasu w roztworze"),
New ADRtyp("2428", "Chloran sodu w roztworze"),
New ADRtyp("2429", "Chloran wapnia w roztworze"),
New ADRtyp("2430", "Alkilofenole"),
New ADRtyp("2431", "o-Anizydyna (o-metoksyanilina)"),
New ADRtyp("2432", "N,N-Dwuetyloanilina (N,N-dwuetylofenyloamina)"),
New ADRtyp("2433", "Chloronitrotolueny"),
New ADRtyp("2438", "Chlorek piwaloilu (chlorek kwasu trójmetylooctowego)"),
New ADRtyp("2442", "Chlorek trójchloroacetylu"),
New ADRtyp("2443", "Tlenotrójchlorek wanadu w roztworze"),
New ADRtyp("2446", "m-Nitrokrezole"),
New ADRtyp("2447", "Fosfor biały stopiony"),
New ADRtyp("2448", "Siarka w stanie stopionym"),
New ADRtyp("2483", "Izocyjanian izopropylu"),
New ADRtyp("2484", "Izocyjanian III-rz. butylu"),
New ADRtyp("2485", "Izocyjanian n-butylu"),
New ADRtyp("2486", "Izocyjanian izobutylu"),
New ADRtyp("2512", "Aminofenole"),
New ADRtyp("2513", "Bromek bromoacetylu"),
New ADRtyp("2514", "Bromobenzen (bromek fenylu)"),
New ADRtyp("2515", "Bromoform"),
New ADRtyp("2516", "Czterobromek węgla"),
New ADRtyp("2517", "1,1,1-Chlorodwufluoroetan (R 142b)"),
New ADRtyp("2520", "Cyklooktadien"),
New ADRtyp("2521", "Dwuketen"),
New ADRtyp("2522", "Metakrylan dwumetyloaminoetylu"),
New ADRtyp("2524", "orto-Mrówczan. etylu"),
New ADRtyp("2525", "Szczawian etylu"),
New ADRtyp("2527", "Akrylan izobutylu"),
New ADRtyp("2528", "Izomaślan izobutylu"),
New ADRtyp("2530", "Bezwodnik kwasu izomasłowego"),
New ADRtyp("2533", "Trójchlorooctan metylu"),
New ADRtyp("2535", "Metylomorfolina"),
New ADRtyp("2536", "Metyloczterowodorofuran"),
New ADRtyp("2539", "Aldehyd oktylowy (oktanal)"),
New ADRtyp("2542", "Trójbutyloamina"),
New ADRtyp("2584", "Kwasy alkilosultonowe lub arylosultonowe zawierające ponad 3% wolnego kwasu siarkowego"),
New ADRtyp("2608", "Nitropropany (mononitropropany)"),
New ADRtyp("2643", "Bromooctan metylu"),
New ADRtyp("2661", "Sześciochloroaceton"),
New ADRtyp("2664", "Bromek metylenu (dwubromometan)"),
New ADRtyp("2669", "Chlorokrezole"),
New ADRtyp("2688", "l-Chloro-3-bromopropan"),
New ADRtyp("2730", "Nitroanizole"),
New ADRtyp("2739", "Bezwodnik kwasu masłowego"),
New ADRtyp("2747", "Chloromrówczan III-rz. butylocykloheksylu"),
New ADRtyp("2748", "Chloromrówczan 2-heksyloetylu"),
New ADRtyp("2758", "Pestycydy na bazie karbaminianu (związki i preparaty) trujące o temperaturze zapłonu niższej niż 32 °C"),
New ADRtyp("2762", "Pestycydy organiczne zawierające chlor (związki i preparaty) trujące o temperaturze zapłonu niższej niż 32 °C")
        }


End Class
